### ISSUE TITLE
Feature: Adding  contributors section to the README.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [AI4Finance-Foundation/FinGPT#109]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/AI4Finance-Foundation/FinGPT/assets/147402107/f9aeba0d-7e4c-4ac5-891b-acde00cae3dd)

**Comment by Kalyanimhala** [comment]
@BruceYanghy  Kindly assign me this issue, I want to work on it. Thank You!!

**Comment by BruceYanghy** [comment]
> @BruceYanghy Kindly assign me this issue, I want to work on it. Thank You!!

Thank you so much for bringing this to our attention and offering your help to enhance our project’s documentation! We wholeheartedly agree that acknowledging the contributions of our community is crucial, and it’s something we are eager to highlight.

We would be delighted to have you work on this, and we really appreciate your initiative! 

Bruce
