### ISSUE TITLE
model load error

### ISSUE THREAD

**Issue by HackerHuangZY** [AI4Finance-Foundation/FinGPT#122]
When I running LORA,ipynb. I have downloaded the chatglm2_6b in local disks, however it raise the error DatasetGenerationError: An error occurred while generating the dataset

**Comment by Weiyao-Li** [comment]
If it is dataset generation error, please take a look at the "dataset" related script and firstly test if this dataset is generated or not. If it has errors like null pointer exception, or NoneType in python. You should start from there.

**Comment by Weiyao-Li** [comment]
> 您好 怎么下载chatglm2_6b

There are 2 ways: remote fetch from hugging face or local download and use.
