### ISSUE TITLE
Issues Using FinGPT/fingpt-forecaster_dow30_llama2-7b_lora

### ISSUE THREAD

**Issue by pschofield2** [AI4Finance-Foundation/FinGPT#124]
Good Day,

First of all, love this project. Thanks for all everyone does who contributes.

I am new to huggingface so thanks for bearing with me. Anyways, I am trying to load the dow30 model but always get the issue: "OSError: base_models/Llama-2-7b-chat-hf is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'". Is there something I am missing?

For example, I get that error when simply running: `pipeline('text-generation','FinGPT/fingpt-forecaster_dow30_llama2-7b_lora')
`
I also try following the Readme for the forecaster, but keep getting a "can't find the .config file"

Any help would be much appreciated!

**Comment by Noir97** [comment]
There were some mistakes in the README instructions, and the code in demo.ipynb was intended for loading models from disk. Now I've corrected them both. Try again and see if there are any more things we can help you with.

**Comment by pschofield2** [comment]
thanks so much for your quick response! I have a follow up question in regards to the .readme line of code:
`model = PeftModel.from_pretrained('FinGPT/fingpt-forecaster_dow30_llama2-7b_lora')
`
I am getting the error: "TypeError: PeftModel.from_pretrained() missing 1 required positional argument: 'model_id'"

Shouldn't the code be:
`model = PeftModel.from_pretrained(base_model,'FinGPT/fingpt-forecaster_dow30_llama2-7b_lora')
`?

**Comment by Noir97** [comment]
> quick response! I have a follow up question in regards to the .readme line of code:
> `model = PeftModel.from_pretrained('FinGPT/fingpt-forecaster_dow30_llama2-7b_lora') `
> I am getting the error: "TypeError: PeftMo

You're right. Thanks for pointing that out, my bad for not reviewing the README codes. Fixing it.
