### ISSUE TITLE
test_dataset = load_from_disk('data/fingpt-forecaster-dow30v3-20221231-20230531-llama/')['test'] 数据是从哪里下载的

### ISSUE THREAD

**Issue by GL-Aronman** [AI4Finance-Foundation/FinGPT#137]
fingpt/FinGPT_Forecaster/demo.ipynb 里面的
test_dataset = load_from_disk('data/fingpt-forecaster-dow30v3-20221231-20230531-llama/')['test']
请问这个数据是从哪里下载的

**Comment by Noir97** [comment]
It's a test split from our generated dataset. But I'm sorry as we currently don't release it. You can try to reproduce a similar dataset with our provided data script `prepare_data.ipynb`. Feel free to reopen the issue if you have further questions.

**Comment by hongxiong1230** [comment]
Hello! I am using the train.sh of the project of FinGPT_Forecaster, but the fine tuned model size is over 100G. The original stock data is about 70M. Do you know how to better obtain the fine tuned model?
