### ISSUE TITLE
FinGPT_Forecaster中prepare_data.ipynb的map_bin_label函数是不是漏了一个加号

### ISSUE THREAD

**Issue by Rinko** [AI4Finance-Foundation/FinGPT#139]
现在变化超过5时代码是：
` if lb.endswith('+'):
        lb = lb.replace('5', 'more than 5%')`
替换出来字符串应该就是
`more than 5%+`
导致后续gpt4_to_llama函数中，对于这种情况，替换prompt的正则匹配不到。

map_bin_label中是否应该多一个加号？
` if lb.endswith('+'):
        lb = lb.replace('5+', 'more than 5%')`

**Comment by Noir97** [comment]
You're right. Thx for pointing out. Fixing it.
