### ISSUE TITLE
Missing Files in FinGPT-Forecaster-Chinese

### ISSUE THREAD

**Issue by liaorihu** [AI4Finance-Foundation/FinGPT#180]
Hello,

@llk010502

I have encountered some missing files while using your project. Specifically:

- The file **"Hs300 news data20240118/filename"** in **line 113** of **Ashare_data_.py**.  Are these news data downloaded from EastMoney similar to those in /FinGPT_v1.0/data_preparations?
- The file **000016.SH-成分及权重-20240411.xlsx** referenced in **In[4]** of **Formulate_training_data_.ipynb** is not provided.
- The  default **train.sh** (Chinese  Forecaster) file is missing.

These missing files are affecting the proper functioning of the project. Could you please add these files or provide relevant download links?  If these files cannot be provided due to copyright reasons, could you  provide the **column names** for 000016.SH-成分及权重-20240411.xlsx?

Thank you very much!

**Comment by llk010502** [comment]
Hi, here are some answers for your reference.
1. the news data was scrapped from estmoney, you may refer the inference data pipe for the data aquisition.
2. '000016.SH-成分及权重-20240411.xlsx' is basically a ticker and name of SSE50 Index stocks. You could find the list yourself.
3. you could refer train_lora.py file for training

**Comment by liaorihu** [comment]
> Hi, here are some answers for your reference.
> 
> 1. the news data was scrapped from estmoney, you may refer the inference data pipe for the data aquisition.
> 2. '000016.SH-成分及权重-20240411.xlsx' is basically a ticker and name of SSE50 Index stocks. You could find the list yourself.
> 3. you could refer train_lora.py file for training

Thank you very much and wish you have a great day!
