### ISSUE TITLE
How to make dataset_title_test.json file?

### ISSUE THREAD

**Issue by asmcos** [AI4Finance-Foundation/FinGPT#19]
I try FinGPT-v1/data_preparations.
I have use add_labels.py make results_with_content/*.csv

How to make dataset_title_test.json? 

I find example: instructions = json.load(open("/root/FinGPT-ChatGLM-Fineturning/data/title/dataset_title_test.json"))
The file is alpaca format ?

**Comment by oliverwang15** [comment]
Hi, [asmcos](https://github.com/asmcos).

We have updated the code and you may find the code for generating the dataset in alpaca format [here](https://github.com/AI4Finance-Foundation/FinGPT/blob/master/fingpt/FinGPT-v1/making_dataset/make_dataset_by_date.ipynb).

**Comment by asmcos** [comment]
Thank you.
