### ISSUE TITLE
Juchao_Annoumcement 拼写错误 请修改为o Juchao_Announcement 

### ISSUE THREAD

**Issue by elven2016** [AI4Finance-Foundation/FinGPT#38]
Juchao_Annoumcement 拼写错误，实际是Juchao_Announcement ，demo文件中多个地方拼写错误，导致无法import‘’
这个示例代码：ChatGPT_Robo_Advisor_v2.ipynb中有2处
1、from finnlp.data_sources.company_announcement.juchao import Juchao_Annoumcement
2、 "downloader = Juchao_Annoumcement()"

**Comment by oliverwang15** [comment]
感谢您的建议！我们已近更新相关代码！
