### ISSUE TITLE
Encountering a bug when using add_label.py

### ISSUE THREAD

**Issue by Createsnow** [AI4Finance-Foundation/FinGPT#46]
**Is your feature request related to a problem? Please describe.**
Hi, I'm encountering an issue when using add_label.py. The code segment df["post_publish_time"] = pd.to_datetime(df["post_publish_time"]) is throwing an error. I checked the csv file under the 'results_with_content' folder and found that all the values of the 'post_publish_time' field are in dictionary format hence cannot be processed by the pd.to_datetime() function. What could be causing this?

csv:
![image](https://github.com/AI4Finance-Foundation/FinGPT/assets/55679629/66f6d9c8-15c5-440d-9b57-d1da6fcfa884)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by asmcos** [comment]
The error from download_contents.py. 
```
res = pd.Series(res).to_frame().T
```
and
```
    df[new_columns] = df.apply(lambda x:get_one_content(x), axis = 1, result_type= "expand", )
```

**Comment by Createsnow** [comment]
thanks,The error occurred at "res = pd.Series(res).to_frame().T" when crawling data previously, so I modified the source code. However, now I understand that it was probably due to anti-scraping measures, resulting in incorrect data formats or corrupted data.

**Comment by Createsnow** [comment]
> download_contents.py 中的错误。
> 
> ```
> res = pd.Series(res).to_frame().T
> ```
> 
> 和
> 
> ```
>     df[new_columns] = df.apply(lambda x:get_one_content(x), axis = 1, result_type= "expand", )
> ```
The error occurred at "res = pd.Series(res).to_frame().T" when crawling data previously, so I modified the source code. However, now I understand that it was probably due to anti-scraping measures, resulting in incorrect data formats or corrupted data.

**Comment by Createsnow** [comment]
> download_contents.py 中的错误。
> 
> ```
> res = pd.Series(res).to_frame().T
> ```
> 
> 和
> 
> ```
>     df[new_columns] = df.apply(lambda x:get_one_content(x), axis = 1, result_type= "expand", )
> ```

thanks!,The error occurred at "res = pd.Series(res).to_frame().T" when crawling data previously, so I modified the source code. However, now I understand that it was probably due to anti-scraping measures, resulting in incorrect data formats or corrupted data.
