### ISSUE TITLE
这个组织中这么多库 Fin-Meta, Fin-NLP, FinRL, Prodracer, FinGPT 对于新手来说应该如何选择？

### ISSUE THREAD

**Issue by Johnson-yue** [AI4Finance-Foundation/FinGPT#51]
感谢团队的分享， 我也看了很多关于AI4Finance的资料，作为一个新手小白，我想入门金融的强化学习，但是被这么多的库砸晕了。

他们都是什么关系，是版本更新，还是并且共存，是否有先后顺序，都处于更新中吗？有更新的优先级吗？
作为一个新手程序员，有些python和pytorch的基础，应该从哪个库入手。
Fin-Meta好像是数据层的， 那么在Fin-RL 和Fin-GPT中的数据层是否还是用Fin-Meta来做的？ 还是每一个库都是独立的？

这些库中，哪个是最新的能学习如何应用强化学习的？

希望能有一篇内容介绍这些库的关系，已经在当下的时间点，学习哪个库才是最合适的选择。谢谢

**Comment by zhumingpassional** [comment]
With respect to RL, pls start from FinRL， FinRL-Meta and FinRL-tutorials,  where FinRL-Meta provides data for FinRL. 

With respect to Fin LLM,  pls start from FinGPT and FinNLP, and FinNLP provides data for FinGPT.

pls refer to https://finrl.readthedocs.io/en/latest/index.html and https://fintips.io/

**Comment by Johnson-yue** [comment]
ok， thank your reply I will learn about FinRL with FinRL-Meta
