### ISSUE TITLE
can not get the ../../stocknet-dataset/tweet/preprocessed/{stock_name}/ file info

### ISSUE THREAD

**Issue by lichao252244354** [AI4Finance-Foundation/FinGPT#6]
HI， when I run the trade_with_gpt3.ipynb ，can't find the ../../stocknet-dataset/tweet/preprocessed/{stock_name}/  Directory ，how to get the stock data ? thank you !

**Comment by lichao252244354** [comment]
` def read_file(self,stock_name):
        # sentences
        sentence_path = f"../../stocknet-dataset/tweet/preprocessed/{stock_name}/"
        self.tweets_df = pd.DataFrame()
        print("missing (empty means not missing):", end = " ")
        for date in pd.date_range(self.start_date,self.end_date):
            date = date.date().strftime("%Y-%m-%d")
            file_path = f"{sentence_path}/{date}"`

**Comment by oliverwang15** [comment]
Hi, lichao. As stated in the [readme file](https://github.com/AI4Finance-Foundation/FinGPT/tree/master/demos/chatgpt-trading-v2#1-data-preparation-for-price-data-and-tweets), you may have to download or `git clone` the data from [stocknet-dataset](https://github.com/yumoxu/stocknet-dataset) first. Then you can find those data in your downloaded or cloned files, and you may change the directory to whatever you want.

**Comment by lichao252244354** [comment]
好的，非常谢谢！
