### ISSUE TITLE
帮忙看一下这个是什么问题，推理的时候数量量大了就出现这个问题。

### ISSUE THREAD

**Issue by shiguangleigithub** [AI4Finance-Foundation/FinGPT#80]
帮忙看一下这个是什么问题，推理的时候数量量大了就出现这个问题。
![1](https://github.com/AI4Finance-Foundation/FinGPT/assets/143694361/8373ad92-ffed-413e-84ca-e0c3e80205df)

**Comment by Noir97** [comment]
It's not because of large number of samples. Its because the total steps is not calculated correctly. 'total_steps = dataset.shape[0]//batch_size + 1' make this error happen when your sample number is divisible by batch_size. We'll fix that later
